<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionsSeeder extends Seeder
{
    public function run()
    {
        $permissions = [
            'posts index',
            'posts create',
            'posts edit',
            'posts delete',
            'slider index',
            'slider create',
            'slider edit',
            'slider delete',
            'directors index',
            'directors create',
            'directors edit',
            'directors delete',
            'about index',
            'about edit',
            'categories index',
            'categories create',
            'categories edit',
            'categories delete',
            'languages index',
            'languages create',
            'languages edit',
            'languages delete',
            'contact-us index',
            'contact-us delete',
            'settings index',
            'settings create',
            'settings edit',
            'settings delete',
            'seo-tags index',
            'seo-tags create',
            'seo-tags edit',
            'seo-tags delete',
            'users index',
            'users create',
            'users edit',
            'users delete',
            'permissions index',
            'permissions create',
            'permissions edit',
            'permissions delete',
            'new-permission index',
            'new-permission create',
            'new-permission edit',
            'new-permission delete',
            'report index',
            'report delete',
            'information index',
            'information create',
            'information edit',
            'information delete',
            'dashboard index',
            'confirm-post',
            'newsletter index',
            'newsletter create',
            'newsletter delete',
            'team index',
            'team create',
            'team edit',
            'team delete',
            'projects create',
            'projects edit',
            'projects delete',
            'projects index',
            'products create',
            'products edit',
            'products delete',
            'products index',
            'alt-categories create',
            'alt-categories edit',
            'alt-categories delete',
            'alt-categories index',
            'vacancy create',
            'vacancy edit',
            'vacancy delete',
            'vacancy index',
            'appeals index',
            'appeals delete',
            'news create',
            'news edit',
            'news delete',
            'news index',
            'corporate create',
            'corporate edit',
            'corporate delete',
            'corporate index',
            'our-success create',
            'our-success edit',
            'our-success delete',
            'our-success index',
            'company-and-products create',
            'company-and-products edit',
            'company-and-products delete',
            'company-and-products index',
            'services create',
            'services edit',
            'services delete',
            'services index',

            'faq create',
            'faq edit',
            'faq delete',
            'faq index',

            'city index',
            'city edit',
            'city create',
            'city delete',
            'salary index',
            'salary edit',
            'salary create',
            'salary delete',
            'education index',
            'education create',
            'education edit',
            'education delete',
            'experience index',
            'experience create',
            'experience edit',
            'experience delete',
            'mode index',
            'mode create',
            'mode edit',
            'mode delete',
            'packages index',
            'packages create',
            'packages edit',
            'packages delete',
            'site-users index',
            'site-users create',
            'site-users edit',
            'site-users delete',
            'term index',
            'term edit',
        ];
        foreach ($permissions as $permission) {
            Permission::create([
                'name' => $permission,
                'guard_name' => 'web',
            ]);
        }
    }
}
